### ISSUE TITLE
compiling problem

### ISSUE THREAD

**Issue by malcamal** [PawelGorny/WifSolverCuda#12]
make all
mkdir -p obj
g++ -std=c++11 -m64 -mssse3 -Wno-unused-result -Wno-write-strings -O2 -I. -I/include -o obj/ripemd160.o -c lib/hash/ripemd160.cpp
g++ -std=c++11 -m64 -mssse3 -Wno-unused-result -Wno-write-strings -O2 -I. -I/include -o obj/ripemd160_sse.o -c lib/hash/ripemd160_sse.cpp
g++ -std=c++11 -m64 -mssse3 -Wno-unused-result -Wno-write-strings -O2 -I. -I/include -o obj/sha256cpp.o -c lib/hash/sha256.cpp
g++ -std=c++11 -m64 -mssse3 -Wno-unused-result -Wno-write-strings -O2 -I. -I/include -o obj/sha256_sse.o -c lib/hash/sha256_sse.cpp
gcc -O3 -c lib/base58.c -o obj/base58.o
lib/base58.c: In function ‘b58enc’:
lib/base58.c:54:14: warning: implicit declaration of function ‘malloc’ [-Wimplicit-function-declaration]
   54 |  buf = (int*)malloc(sizeof(uint8_t) * size);
      |              ^~~~~~
lib/base58.c:54:14: warning: incompatible implicit declaration of built-in function ‘malloc’
lib/base58.c:20:1: note: include ‘<stdlib.h>’ or provide a declaration of ‘malloc’
   19 | #include "base58.h"
  +++ |+#include <stdlib.h>
   20 | 
lib/base58.c:54:6: warning: assignment to ‘uint8_t *’ {aka ‘unsigned char *’} from incompatible pointer type ‘int *’ [-Wincompatible-pointer-types]
   54 |  buf = (int*)malloc(sizeof(uint8_t) * size);
      |      ^
lib/base58.c:85:2: warning: implicit declaration of function ‘free’ [-Wimplicit-function-declaration]
   85 |  free(buf);
      |  ^~~~
lib/base58.c:85:2: warning: incompatible implicit declaration of built-in function ‘free’
lib/base58.c:85:2: note: include ‘<stdlib.h>’ or provide a declaration of ‘free’
lib/base58.c: In function ‘b58tobin’:
lib/base58.c:96:15: warning: incompatible implicit declaration of built-in function ‘malloc’
   96 |  outi = (int*)malloc(sizeof(b58_almostmaxint_t) * outisz);
      |               ^~~~~~
lib/base58.c:96:15: note: include ‘<stdlib.h>’ or provide a declaration of ‘malloc’
g++ -O3 -c lib/util.cpp -o obj/util.o
g++ -std=c++11 -m64 -mssse3 -Wno-unused-result -Wno-write-strings -O2 -I. -I/include -c lib/Int.cpp -o obj/Int.o
g++ -std=c++11 -m64 -mssse3 -Wno-unused-result -Wno-write-strings -O2 -I. -I/include -c lib/Point.cpp -o obj/Point.o
g++ -std=c++11 -m64 -mssse3 -Wno-unused-result -Wno-write-strings -O2 -I. -I/include -c lib/SECP256K1.cpp -o obj/SECP256K1.o
g++ -std=c++11 -m64 -mssse3 -Wno-unused-result -Wno-write-strings -O2 -I. -I/include -c lib/IntGroup.cpp -o obj/IntGroup.o
g++ -std=c++11 -m64 -mssse3 -Wno-unused-result -Wno-write-strings -O2 -I. -I/include -c lib/IntMod.cpp -o obj/IntMod.o
nvcc --ptxas-options=-v -maxrregcount=0 --compile --compiler-options -fPIC -ccbin /usr/bin/g++9 -m64 -O2 -I/include 	-gencode=arch=compute_61,code=sm_61 -o obj/sha256.o -c lib/hash/sha256.cu
make: nvcc: Command not found
make: *** [Makefile:29: all] Error 127
Question : what i am doing wrong ? please help

**Comment by PawelGorny** [comment]
Do you have 'nvcc' in path? If you are sure it is properly installed, change the path in Makefile
https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html

**Comment by malcamal** [comment]
COMPUTE_CAP=61
NVCC=$(CUDA)/usr/local/cuda-11.6/bin/nvcc

After I edited Makefile , everything works 
Thank you for getting knowledge

**Comment by malcamal** [comment]
COMPUTE_CAP=61
NVCC=$(CUDA)/usr/local/cuda-11.6/bin/nvcc

After I edited Makefile , everything works
Thank you for getting knowledge
