### ISSUE TITLE
p2wpkh address?

### ISSUE THREAD

**Issue by Vantorn** [PawelGorny/WifSolverCuda#13]
Hello
How to proceed if the address is p2wpkh?

**Comment by PawelGorny** [comment]
Hi
Currently only legacy and P2SH (3...) addresses are supported, bech32 not yet. I have added it to my TODO list!

**Comment by PawelGorny** [comment]
Added!
https://github.com/PawelGorny/WifSolverCuda/releases/tag/v0.5.3

**Comment by Vantorn** [comment]
Thanks
Can you add a feature to find all valid WIFs in a range?
Like what the following programs do with CPU:
https://github.com/phrutis/Fialka
https://github.com/Coding-Enthusiast/FinderOuter

**Comment by Vantorn** [comment]
Great👍
Exactly what I meant
