### ISSUE TITLE
How to calculate stride? 

### ISSUE THREAD

**Issue by Starblue0** [PawelGorny/WifSolverCuda#15]
How would we Calculate the stride? 
I am confused on how to find the stride. 

I have a private key that is a 56% match with the public address I am trying to recover. 

I have the Private key of this address 156nQNtSdLMsng6HqTFiavcMb2uQLHP6VD and it is a	 56% Match to the public key of this address 156nQNtSdLMsqD81zpjzzbHKonqgtBwVJq (Address I am trying to recover).

How would I calculate the stride for the address I am trying to the recover with the Private key and address I have now. Since it is a 56% match. 

Please help me learn on how to find the stride for this.

**Comment by Starblue0** [comment]
I did read the Stride.txt. I am just confused on how to calculate the right one since it is %56 matching,

**Comment by PawelGorny** [comment]
I am not afraid I do not understand.
In general stride is 56^(number of known characters on the end). Program works only if checksum from decoded WIF is known, which means there must be at least 5-6-7 characters known at the end. So, Program will work for WIF |???xxxxx| or |xxxx???xxxx|, but not when the whole ending is not known |xxxx????|. For that case, other solution must be used.
I do not understand what do you say about 56% match of public key.
You may send me an email with details, I am not sure if now I may help.
