### ISSUE TITLE
multi Address

### ISSUE THREAD

**Issue by Brodasdasd** [PawelGorny/WifSolverCuda#17]
hi, i want to slove 3 Address, how i can do it.

**Comment by PawelGorny** [comment]
Currently you may target only one address. Or you may not use any address at all and then check results file for hits. But as adding multi-address is not complicated, I will try to prepare a new version soon.

**Comment by PawelGorny** [comment]
https://github.com/PawelGorny/WifSolverCuda/releases/tag/v0.6.2
