### ISSUE TITLE
Nvidia A100 compatibility

### ISSUE THREAD

**Issue by GraverErmitage** [PawelGorny/WifSolverCuda#20]
Hi Pawel,

Could you please compile the program with compatibility for Nvidia A100 GPU?
![image](https://user-images.githubusercontent.com/34091165/210975697-299f9987-e59b-48c3-99f1-c18e6be92672.png)

BR
Sergey

**Comment by PawelGorny** [comment]
Binary file is already prepared for A100.
Which CUDA version do you use? If you use vast, try to use image "[nvidia/cuda:11.5.2-base-ubuntu20.04]".

**Comment by GraverErmitage** [comment]
Hi Pawel,

I used the version of the OS image you supposed. It works for NVIDIA A100-PCIE-40GB, but doesn't work for NVIDIA A100-SXM4-80GB.
Please check it.

**Comment by GraverErmitage** [comment]
Hi Pawel,
I tried twice to write you personally to improve the program but it seems you didn't see my messages.
Please let me know how can I contact you personally.
