### ISSUE TITLE
Suggestions for the project WifSolverCuda

### ISSUE THREAD

**Issue by phrutis** [PawelGorny/WifSolverCuda#4]
Hi Pavel. 
I am engaged in the implementation of similar projects to search for WIF keys and not only.
[Fialka M-125](https://github.com/phrutis/Fialka)
[Rotor-Cuda](https://github.com/phrutis/Rotor-Cuda)
[Collider GPU](https://github.com/phrutis/Collider)
1. You are building on CUDA 11.5, so the program will only work on RTX3 GPUs... all other cards will have a carnel image error.
Build like me on CUDA 10.22 will work on all GPUs.
2. I suggest adding a bloom filter to your project. You can take the finished bloom filter code for the GPU from me.
3. There are suggestions how to speed up WIF search by 5 times.

There are many interesting non-public ideas that we can discuss in the telegram group. https://t.me/+_mnQmgS1D5QyYmY6

**Comment by PawelGorny** [comment]
Thanks, I will take a look at Fialka.
I am not sure if I need bloom filter, my idea was to limit number of real key detection, just base on hash. But I will check your suggestions.
About Cuda - code does not depend on 11.6, for Linux you may build it without any changes, on Windows it is quick change. Anyway I think your suggestion is good, for the next releases I will prepare build for older cards also.
