### ISSUE TITLE
Recover a p2sh address?

### ISSUE THREAD

**Issue by farway2b** [PawelGorny/WifSolverCuda#9]
Hello
I've tested this wif solver and found that only works with legacy addresses.
For a segwit address (bc1q) there is no problem, because we can find the related legacy address with the same hash160.
How to recover the Wif of a p2sh address?

**Comment by PawelGorny** [comment]
Good question, I will try to add it.

**Comment by phrutis** [comment]
Can you also try using the public key? I will close my question.

**Comment by farway2b** [comment]
Thanks for your great job👍
I asked, because we have such a case. my brother had saved his addresses WIFs in 5 parts but one of them was lost!
And since no tx has been done so far, we do not have the pub key of the p2sh address to generate the related legacy address and recover with this Wif solver.

**Comment by PawelGorny** [comment]
Please check release 0.4.8 
https://github.com/PawelGorny/WifSolverCuda/releases/tag/v0.4.8
I have tried to generate address with https://kimbatt.github.io/btc-address-generator/ and it was found, so I hope it will be useful in your case (depends on script...).
Email me if you need any other help.
